//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowToAudiTrail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public System.Guid AuditID { get; set; }
        public string UserName { get; set; }
        public string IpAddress { get; set; }
        public string AreaAccessed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
